name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ソースコードを取得
      - name: Checkout
        uses: actions/checkout@v4

      # Node.jsをインストール
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # ライブラリをインストール
      - name: Install dependencies
        run: npm install

      #テスト
      - name: Test
        run: npm run test -- --run

      # Viteでビルド
      - name: Build
        run: npm run build

      # Firebase CLIをインストール
      - name: Install Firebase CLI
        run: npm install -g firebase-tools@13.35.1

      # Firebaseへデプロイ
      - name: Deploy
        run: firebase deploy --only hosting --project study-record-940e0 --token "${{ secrets.FIREBASE_TOKEN }}"

